# Generated by Django 4.0.4 on 2022-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tables', '0004_kontrolraporu'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='rapor_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
