# Generated by Django 4.0.4 on 2022-05-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_tables', '0006_remove_kontrolraporu_acik_montaj_is_emri_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontrolraporu',
            name='transfer_adet',
        ),
    ]
