# Generated by Django 4.0.4 on 2022-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_tables', '0007_remove_kontrolraporu_transfer_adet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parca_kodu_listesi',
            name='birim',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parca_kodu_listesi',
            name='parca_tipi',
            field=models.CharField(max_length=40),
        ),
    ]
